---
 - hosts: all 
   tasks: 
    - name: My 2nd Playbook
      ios_command:
       commands: 
        - show version
        - show ip int br
        - show run
        - show clock

    - name: ping google dnc
      ios_command:
       commands:
        - show ip route
      register: output
    
    - name: show normal output
      debug: 
      # msg: "hello world" 
       var: output
      debug:
        msg: "hello World"



